<a href="https://colab.research.google.com/github/Farsana-svg/learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
#please provide your answer below this line.
import numpy as np
x = np.arange(6,15).reshape(3,3)
print(x)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [11]:
#please provide your answer below this line.
import numpy as np
x = np.arange(6,22).reshape(4,4)
print(x)
y = np.arange(3,19).reshape(4,4)
print(y)
x = np.arange(6,22).reshape(2,8)
y = np.arange(3,19).reshape(2,8)
p = np.vstack((x,y))
print(p)
q = np.hstack((x,y))
print(q)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]
 [ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]]
[[ 6  7  8  9 10 11 12 13  3  4  5  6  7  8  9 10]
 [14 15 16 17 18 19 20 21 11 12 13 14 15 16 17 18]]
